// 基礎單字庫：給字母練習 / 單字辨識 / 填空 / 聽力題共用
export const WORDS = [
  { word: 'APPLE', emoji: '🍎', letter: 'A' },
  { word: 'BALL', emoji: '⚽', letter: 'B' },
  { word: 'CAT', emoji: '🐱', letter: 'C' },
  { word: 'DOG', emoji: '🐶', letter: 'D' },
  { word: 'EGG', emoji: '🥚', letter: 'E' },
  { word: 'FISH', emoji: '🐟', letter: 'F' },
  { word: 'GRAPE', emoji: '🍇', letter: 'G' },
  { word: 'HAT', emoji: '🎩', letter: 'H' },
  { word: 'ICECREAM', emoji: '🍦', letter: 'I' },
  { word: 'JUICE', emoji: '🧃', letter: 'J' },
  { word: 'KITE', emoji: '🪁', letter: 'K' },
  { word: 'LION', emoji: '🦁', letter: 'L' },
  { word: 'MOON', emoji: '🌙', letter: 'M' },
  { word: 'NEST', emoji: '🪹', letter: 'N' },
  { word: 'ORANGE', emoji: '🍊', letter: 'O' },
  { word: 'PIG', emoji: '🐷', letter: 'P' },
  { word: 'QUEEN', emoji: '👑', letter: 'Q' },
  { word: 'RABBIT', emoji: '🐰', letter: 'R' },
  { word: 'SUN', emoji: '☀️', letter: 'S' },
  { word: 'TIGER', emoji: '🐯', letter: 'T' },
  { word: 'UMBRELLA', emoji: '☂️', letter: 'U' },
  { word: 'VAN', emoji: '🚐', letter: 'V' },
  { word: 'WATERMELON', emoji: '🍉', letter: 'W' },
  { word: 'YOYO', emoji: '🪀', letter: 'Y' },
  { word: 'ZEBRA', emoji: '🦓', letter: 'Z' },
]

export const SENTENCE_TEMPLATES = ['I have a ___.', 'I see a ___.', 'I like ___.', 'Look at the ___!']
